import { blurDataUrls } from './data-blur';

export type ImageSizes = {
  xs: string;
  sm: string;
  md: string;
  lg: string;
  xl: string;
  full: string;
};

export type ExifData = {
  camera?: string;
  lens?: string;
  aperture?: string;
  exposureTime?: string;
  iso?: string;
  exposureComp?: string;
  focalLength?: string;
};

export type ImageItem = {
  title: string;
  slug: string;
  uri: string;
  sizes?: ImageSizes;
  size?: { width: number; height: number; aspect: number };
  location?: string;
  exif?: ExifData;
  icons?: string[];
  blurDataURL?: string;
};

export type GalleryItems = ImageItem[];

export type GalleryItemsMap = Map<string, ImageItem>;

export type PlaylistItem = {
  title: string;
  artist: string;
  image: string;
};

export type PlaylistItems = PlaylistItem[];

export const imgGroup1: GalleryItems = [
  {
    title: 'Sounds Lost Their Meaning',
    slug: 'sounds-lost-their-meaning',
    uri: 'https://d3fo8poitgfhx4.cloudfront.net/photos/sounds-lost-their-meaning.jpg?ver=1',
    sizes: {
      xs: 'https://d3fo8poitgfhx4.cloudfront.net/photos/sounds-lost-their-meaning-w_300.jpg',
      sm: 'https://d3fo8poitgfhx4.cloudfront.net/photos/sounds-lost-their-meaning-w_450.jpg',
      md: 'https://d3fo8poitgfhx4.cloudfront.net/photos/sounds-lost-their-meaning-w_600.jpg',
      lg: 'https://d3fo8poitgfhx4.cloudfront.net/photos/sounds-lost-their-meaning-w_768.jpg',
      xl: 'https://d3fo8poitgfhx4.cloudfront.net/photos/sounds-lost-their-meaning-w_1000.jpg',
      full: 'https://d3fo8poitgfhx4.cloudfront.net/photos/sounds-lost-their-meaning.jpg?ver=1',
    },
    size: { width: 2000, height: 3555, aspect: Math.floor(2000 / 3555) },
    exif: {
      camera: 'FUJIFILM X-S10',
      lens: 'FUJINON XF 70-300mm F4-5.6',
      aperture: 'f/4',
      exposureTime: '1/180 sec',
      iso: 'ISO-320',
      exposureComp: '0 EV',
      focalLength: '70mm',
    },
    location: 'Istanbul, Turkey',
  },
  {
    title: 'Colors Lost Their Meaning',
    slug: 'colors-lost-their-meaning',
    uri: 'https://d3fo8poitgfhx4.cloudfront.net/photos/colors-lost-their-meaning.jpg?ver=1',
    sizes: {
      xs: 'https://d3fo8poitgfhx4.cloudfront.net/photos/colors-lost-their-meaning-w_300.jpg',
      sm: 'https://d3fo8poitgfhx4.cloudfront.net/photos/colors-lost-their-meaning-w_450.jpg',
      md: 'https://d3fo8poitgfhx4.cloudfront.net/photos/colors-lost-their-meaning-w_600.jpg',
      lg: 'https://d3fo8poitgfhx4.cloudfront.net/photos/colors-lost-their-meaning-w_768.jpg',
      xl: 'https://d3fo8poitgfhx4.cloudfront.net/photos/colors-lost-their-meaning-w_1000.jpg',
      full: 'https://d3fo8poitgfhx4.cloudfront.net/photos/colors-lost-their-meaning.jpg?ver=1',
    },
    size: { width: 2000, height: 3000, aspect: Math.floor(2000 / 3000) },
    exif: {
      camera: 'FUJIFILM X-S10',
      lens: 'FUJINON XF 70-300mm F4-5.6',
      aperture: 'f/4',
      exposureTime: '1/160 sec',
      iso: 'ISO-400',
      exposureComp: '0 EV',
      focalLength: '70mm',
    },
    location: 'Istanbul, Turkey',
  },
  {
    title: 'Waves Lost Their Meaning',
    slug: 'waves-lost-their-meaning',
    uri: 'https://d3fo8poitgfhx4.cloudfront.net/photos/waves-lost-their-meaning.jpg?ver=1',
    sizes: {
      xs: 'https://d3fo8poitgfhx4.cloudfront.net/photos/waves-lost-their-meaning-w_300.jpg',
      sm: 'https://d3fo8poitgfhx4.cloudfront.net/photos/waves-lost-their-meaning-w_450.jpg',
      md: 'https://d3fo8poitgfhx4.cloudfront.net/photos/waves-lost-their-meaning-w_600.jpg',
      lg: 'https://d3fo8poitgfhx4.cloudfront.net/photos/waves-lost-their-meaning-w_768.jpg',
      xl: 'https://d3fo8poitgfhx4.cloudfront.net/photos/waves-lost-their-meaning-w_1000.jpg',
      full: 'https://d3fo8poitgfhx4.cloudfront.net/photos/waves-lost-their-meaning.jpg?ver=1',
    },
    size: { width: 2000, height: 1333, aspect: Math.floor(2000 / 1333) },
    exif: {
      camera: 'FUJIFILM X-S10',
      lens: 'FUJINON XF 70-300mm F4-5.6',
      aperture: 'f/8',
      exposureTime: '1/1000 sec',
      iso: 'ISO-320',
      exposureComp: '+0.3 EV',
      focalLength: '114 mm',
    },
    location: 'Istanbul, Turkey',
  },
  {
    title: 'Clock Tower Bleeds',
    slug: 'clock-tower-bleeds',
    uri: 'https://d3fo8poitgfhx4.cloudfront.net/photos/clock-tower-bleeds.jpg?ver=1',
    sizes: {
      xs: 'https://d3fo8poitgfhx4.cloudfront.net/photos/clock-tower-bleeds-w_300.jpg',
      sm: 'https://d3fo8poitgfhx4.cloudfront.net/photos/clock-tower-bleeds-w_450.jpg',
      md: 'https://d3fo8poitgfhx4.cloudfront.net/photos/clock-tower-bleeds-w_600.jpg',
      lg: 'https://d3fo8poitgfhx4.cloudfront.net/photos/clock-tower-bleeds-w_768.jpg',
      xl: 'https://d3fo8poitgfhx4.cloudfront.net/photos/clock-tower-bleeds-w_1000.jpg',
      full: 'https://d3fo8poitgfhx4.cloudfront.net/photos/clock-tower-bleeds.jpg?ver=1',
    },
    size: { width: 2000, height: 3000, aspect: Math.floor(2000 / 3000) },
    exif: {
      camera: 'FUJIFILM X-S10',
      lens: 'FUJINON XF 18-55mm F2.8-4',
      aperture: 'f/7.1',
      exposureTime: '0.8 sec',
      iso: 'ISO-200',
      exposureComp: '0 EV',
      focalLength: '26mm',
    },
    location: 'Istanbul, Turkey',
  },
  {
    title: 'Smells Lost Their Meaning',
    slug: 'smells-lost-their-meaning',
    uri: 'https://d3fo8poitgfhx4.cloudfront.net/photos/smells-lost-their-meaning.jpg?ver=1',
    sizes: {
      xs: 'https://d3fo8poitgfhx4.cloudfront.net/photos/smells-lost-their-meaning-w_300.jpg',
      sm: 'https://d3fo8poitgfhx4.cloudfront.net/photos/smells-lost-their-meaning-w_450.jpg',
      md: 'https://d3fo8poitgfhx4.cloudfront.net/photos/smells-lost-their-meaning-w_600.jpg',
      lg: 'https://d3fo8poitgfhx4.cloudfront.net/photos/smells-lost-their-meaning-w_768.jpg',
      xl: 'https://d3fo8poitgfhx4.cloudfront.net/photos/smells-lost-their-meaning-w_1000.jpg',
      full: 'https://d3fo8poitgfhx4.cloudfront.net/photos/smells-lost-their-meaning.jpg?ver=1',
    },
    size: { width: 2000, height: 1333, aspect: Math.floor(2000 / 1333) },
    exif: {
      camera: 'FUJIFILM X-S10',
      lens: 'FUJINON XF 70-300mm F4-5.6',
      aperture: 'f/7.1',
      exposureTime: '1/160 sec',
      iso: 'ISO-640',
      exposureComp: '+0.3 EV',
      focalLength: '206mm',
    },
    location: 'Istanbul, Turkey',
  },
  {
    title: 'Moving Lost Its Meaning',
    slug: 'moving-lost-its-meaning',
    uri: 'https://d3fo8poitgfhx4.cloudfront.net/photos/moving-lost-its-meaning.jpg?ver=1',
    sizes: {
      xs: 'https://d3fo8poitgfhx4.cloudfront.net/photos/moving-lost-its-meaning-w_300.jpg',
      sm: 'https://d3fo8poitgfhx4.cloudfront.net/photos/moving-lost-its-meaning-w_450.jpg',
      md: 'https://d3fo8poitgfhx4.cloudfront.net/photos/moving-lost-its-meaning-w_600.jpg',
      lg: 'https://d3fo8poitgfhx4.cloudfront.net/photos/moving-lost-its-meaning-w_768.jpg',
      xl: 'https://d3fo8poitgfhx4.cloudfront.net/photos/moving-lost-its-meaning-w_1000.jpg',
      full: 'https://d3fo8poitgfhx4.cloudfront.net/photos/moving-lost-its-meaning.jpg?ver=1',
    },
    size: { width: 2000, height: 3000, aspect: Math.floor(2000 / 3000) },
    exif: {
      camera: 'FUJIFILM X-S10',
      lens: 'FUJINON XF 70-300mm F4-5.6',
      aperture: 'f/5.6',
      exposureTime: '1/105 sec',
      iso: 'ISO-400',
      exposureComp: '0 EV',
      focalLength: '300mm',
    },
    location: 'Istanbul, Turkey',
  },
  {
    title: 'Tastes Lost Their Meaning',
    slug: 'tastes-lost-their-meaning',
    uri: 'https://d3fo8poitgfhx4.cloudfront.net/photos/tastes-lost-their-meaning.jpg?ver=1',
    sizes: {
      xs: 'https://d3fo8poitgfhx4.cloudfront.net/photos/tastes-lost-their-meaning-w_300.jpg',
      sm: 'https://d3fo8poitgfhx4.cloudfront.net/photos/tastes-lost-their-meaning-w_450.jpg',
      md: 'https://d3fo8poitgfhx4.cloudfront.net/photos/tastes-lost-their-meaning-w_600.jpg',
      lg: 'https://d3fo8poitgfhx4.cloudfront.net/photos/tastes-lost-their-meaning-w_768.jpg',
      xl: 'https://d3fo8poitgfhx4.cloudfront.net/photos/tastes-lost-their-meaning-w_1000.jpg',
      full: 'https://d3fo8poitgfhx4.cloudfront.net/photos/tastes-lost-their-meaning.jpg?ver=1',
    },
    size: { width: 2000, height: 3000, aspect: Math.floor(2000 / 3000) },
    exif: {
      camera: 'FUJIFILM X-S10',
      lens: 'FUJINON XF 70-300mm F4-5.6',
      aperture: 'f/7.1',
      exposureTime: '1/900 sec',
      iso: 'ISO-320',
      exposureComp: '+0.3 EV',
      focalLength: '70mm',
    },
    location: 'Istanbul, Turkey',
  },
  {
    title: 'Hobbies Lost Their Meaning',
    slug: 'hobbies-lost-their-meaning',
    uri: 'https://d3fo8poitgfhx4.cloudfront.net/photos/hobbies-lost-their-meaning.jpg?ver=1',
    sizes: {
      xs: 'https://d3fo8poitgfhx4.cloudfront.net/photos/hobbies-lost-their-meaning-w_300.jpg',
      sm: 'https://d3fo8poitgfhx4.cloudfront.net/photos/hobbies-lost-their-meaning-w_450.jpg',
      md: 'https://d3fo8poitgfhx4.cloudfront.net/photos/hobbies-lost-their-meaning-w_600.jpg',
      lg: 'https://d3fo8poitgfhx4.cloudfront.net/photos/hobbies-lost-their-meaning-w_768.jpg',
      xl: 'https://d3fo8poitgfhx4.cloudfront.net/photos/hobbies-lost-their-meaning-w_1000.jpg',
      full: 'https://d3fo8poitgfhx4.cloudfront.net/photos/hobbies-lost-their-meaning.jpg?ver=1',
    },
    size: { width: 2000, height: 1333, aspect: Math.floor(2000 / 1333) },
    exif: {
      camera: 'FUJIFILM X-S10',
      lens: 'FUJINON XF 70-300mm F4-5.6',
      aperture: 'f/7.1',
      exposureTime: '1/200 sec',
      iso: 'ISO-400',
      exposureComp: '0 EV',
      focalLength: '199mm',
    },
    location: 'Istanbul, Turkey',
  },
  {
    title: 'Warmth Lost Its Meaning',
    slug: 'warmth-lost-its-meaning',
    uri: 'https://d3fo8poitgfhx4.cloudfront.net/photos/warmth-lost-its-meaning.jpg?ver=1',
    sizes: {
      xs: 'https://d3fo8poitgfhx4.cloudfront.net/photos/warmth-lost-its-meaning-w_300.jpg',
      sm: 'https://d3fo8poitgfhx4.cloudfront.net/photos/warmth-lost-its-meaning-w_450.jpg',
      md: 'https://d3fo8poitgfhx4.cloudfront.net/photos/warmth-lost-its-meaning-w_600.jpg',
      lg: 'https://d3fo8poitgfhx4.cloudfront.net/photos/warmth-lost-its-meaning-w_768.jpg',
      xl: 'https://d3fo8poitgfhx4.cloudfront.net/photos/warmth-lost-its-meaning-w_1000.jpg',
      full: 'https://d3fo8poitgfhx4.cloudfront.net/photos/warmth-lost-its-meaning.jpg?ver=1',
    },
    size: { width: 2000, height: 1333, aspect: Math.floor(2000 / 1333) },
    exif: {
      camera: 'FUJIFILM X-S10',
      lens: 'FUJINON XF 70-300mm F4-5.6',
      aperture: 'f/9',
      exposureTime: '1/180 sec',
      iso: 'ISO-160',
      exposureComp: '0 EV',
      focalLength: '127mm',
    },
    location: 'Istanbul, Turkey',
  },
];

export const imgGroup2: GalleryItems = [
  {
    title: 'Crane Sunset Skyline',
    slug: 'crane-sunset-skyline',
    uri: 'https://d3fo8poitgfhx4.cloudfront.net/photos/crane-sunset-skyline.jpg?ver=1',
    sizes: {
      xs: 'https://d3fo8poitgfhx4.cloudfront.net/photos/crane-sunset-skyline-w_300.jpg',
      sm: 'https://d3fo8poitgfhx4.cloudfront.net/photos/crane-sunset-skyline-w_450.jpg',
      md: 'https://d3fo8poitgfhx4.cloudfront.net/photos/crane-sunset-skyline-w_600.jpg',
      lg: 'https://d3fo8poitgfhx4.cloudfront.net/photos/crane-sunset-skyline-w_768.jpg',
      xl: 'https://d3fo8poitgfhx4.cloudfront.net/photos/crane-sunset-skyline-w_1000.jpg',
      full: 'https://d3fo8poitgfhx4.cloudfront.net/photos/crane-sunset-skyline.jpg?ver=1',
    },
    size: { width: 2000, height: 1333, aspect: Math.floor(2000 / 1333) },
    exif: {
      camera: 'FUJIFILM X-S10',
      lens: 'FUJINON XF 70-300mm F4-5.6',
      aperture: 'f/8',
      exposureTime: '1/3500 sec',
      iso: 'ISO-320',
      exposureComp: '-1.3 EV',
      focalLength: '185mm',
    },
    location: 'Istanbul, Turkey',
  },
  {
    title: 'Antique Shop with Red Door',
    slug: 'antique-shop-with-red-door',
    uri: 'https://d3fo8poitgfhx4.cloudfront.net/photos/antique-shop-with-red-door.jpg?ver=1',
    sizes: {
      xs: 'https://d3fo8poitgfhx4.cloudfront.net/photos/antique-shop-with-red-door-w_300.jpg',
      sm: 'https://d3fo8poitgfhx4.cloudfront.net/photos/antique-shop-with-red-door-w_450.jpg',
      md: 'https://d3fo8poitgfhx4.cloudfront.net/photos/antique-shop-with-red-door-w_600.jpg',
      lg: 'https://d3fo8poitgfhx4.cloudfront.net/photos/antique-shop-with-red-door-w_768.jpg',
      xl: 'https://d3fo8poitgfhx4.cloudfront.net/photos/antique-shop-with-red-door-w_1000.jpg',
      full: 'https://d3fo8poitgfhx4.cloudfront.net/photos/antique-shop-with-red-door.jpg?ver=1',
    },
    size: { width: 2000, height: 3000, aspect: Math.floor(2000 / 3000) },
    exif: {
      camera: 'FUJIFILM X-S10',
      lens: 'FUJINON XF 70-300mm F4-5.6',
      aperture: 'f/7.1',
      exposureTime: '1/55 sec',
      iso: 'ISO-400',
      exposureComp: '0 EV',
      focalLength: '70mm',
    },
    location: 'Ayvalık, Turkey',
  },
  {
    title: 'Antique Shop Entrance with Red Door',
    slug: 'antique-shop-entrance-with-red-door',
    uri: 'https://d3fo8poitgfhx4.cloudfront.net/photos/antique-shop-entrance-with-red-door.jpg?ver=1',
    sizes: {
      xs: 'https://d3fo8poitgfhx4.cloudfront.net/photos/antique-shop-entrance-with-red-door-w_300.jpg',
      sm: 'https://d3fo8poitgfhx4.cloudfront.net/photos/antique-shop-entrance-with-red-door-w_450.jpg',
      md: 'https://d3fo8poitgfhx4.cloudfront.net/photos/antique-shop-entrance-with-red-door-w_600.jpg',
      lg: 'https://d3fo8poitgfhx4.cloudfront.net/photos/antique-shop-entrance-with-red-door-w_768.jpg',
      xl: 'https://d3fo8poitgfhx4.cloudfront.net/photos/antique-shop-entrance-with-red-door-w_1000.jpg',
      full: 'https://d3fo8poitgfhx4.cloudfront.net/photos/antique-shop-entrance-with-red-door.jpg?ver=1',
    },
    size: { width: 2000, height: 3000, aspect: Math.floor(2000 / 3000) },
    exif: {
      camera: 'FUJIFILM X-S10',
      lens: 'FUJINON XF 70-300mm F4-5.6',
      aperture: 'f/7.1',
      exposureTime: '1/400 sec',
      iso: 'ISO-320',
      exposureComp: '0 EV',
      focalLength: '70mm',
    },
    location: 'Ayvalık, Turkey',
  },
  {
    title: 'Old Soda Factory in Narrow Street',
    slug: 'old-soda-factory-in-narrow-street',
    uri: 'https://d3fo8poitgfhx4.cloudfront.net/photos/old-soda-factory-in-narrow-street.jpg?ver=1',
    sizes: {
      xs: 'https://d3fo8poitgfhx4.cloudfront.net/photos/old-soda-factory-in-narrow-street-w_300.jpg',
      sm: 'https://d3fo8poitgfhx4.cloudfront.net/photos/old-soda-factory-in-narrow-street-w_450.jpg',
      md: 'https://d3fo8poitgfhx4.cloudfront.net/photos/old-soda-factory-in-narrow-street-w_600.jpg',
      lg: 'https://d3fo8poitgfhx4.cloudfront.net/photos/old-soda-factory-in-narrow-street-w_768.jpg',
      xl: 'https://d3fo8poitgfhx4.cloudfront.net/photos/old-soda-factory-in-narrow-street-w_1000.jpg',
      full: 'https://d3fo8poitgfhx4.cloudfront.net/photos/old-soda-factory-in-narrow-street.jpg?ver=1',
    },
    size: { width: 2000, height: 3000, aspect: Math.floor(2000 / 3000) },
    exif: {
      camera: 'FUJIFILM X-S10',
      lens: 'FUJINON XF 70-300mm F4-5.6',
      aperture: 'f/7.1',
      exposureTime: '1/450 sec',
      iso: 'ISO-320',
      exposureComp: '0 EV',
      focalLength: '171mm',
    },
    location: 'Ayvalık, Turkey',
  },
  {
    title: 'Rafts in a Valley',
    slug: 'rafts-in-a-valley',
    uri: 'https://d3fo8poitgfhx4.cloudfront.net/photos/rafts-in-a-valley.jpg?ver=1',
    sizes: {
      xs: 'https://d3fo8poitgfhx4.cloudfront.net/photos/rafts-in-a-valley-w_300.jpg',
      sm: 'https://d3fo8poitgfhx4.cloudfront.net/photos/rafts-in-a-valley-w_450.jpg',
      md: 'https://d3fo8poitgfhx4.cloudfront.net/photos/rafts-in-a-valley-w_600.jpg',
      lg: 'https://d3fo8poitgfhx4.cloudfront.net/photos/rafts-in-a-valley-w_768.jpg',
      xl: 'https://d3fo8poitgfhx4.cloudfront.net/photos/rafts-in-a-valley-w_1000.jpg',
      full: 'https://d3fo8poitgfhx4.cloudfront.net/photos/rafts-in-a-valley.jpg?ver=1',
    },
    size: { width: 2000, height: 3000, aspect: Math.floor(2000 / 3000) },
    exif: {
      camera: 'FUJIFILM X-S10',
      lens: 'FUJINON XF 18-55mm F2.8-4',
      aperture: 'f/10',
      exposureTime: '1/105 sec',
      iso: 'ISO-320',
      exposureComp: '+0.7 EV',
      focalLength: '20mm',
    },
    location: 'Skopje, North Macedonia',
    icons: ['favorite'],
  },
  {
    title: 'Lake by the Mountains',
    slug: 'lake-by-the-mountains',
    uri: 'https://d3fo8poitgfhx4.cloudfront.net/photos/lake-by-the-mountains.jpg?ver=1',
    sizes: {
      xs: 'https://d3fo8poitgfhx4.cloudfront.net/photos/lake-by-the-mountains-w_300.jpg',
      sm: 'https://d3fo8poitgfhx4.cloudfront.net/photos/lake-by-the-mountains-w_450.jpg',
      md: 'https://d3fo8poitgfhx4.cloudfront.net/photos/lake-by-the-mountains-w_600.jpg',
      lg: 'https://d3fo8poitgfhx4.cloudfront.net/photos/lake-by-the-mountains-w_768.jpg',
      xl: 'https://d3fo8poitgfhx4.cloudfront.net/photos/lake-by-the-mountains-w_1000.jpg',
      full: 'https://d3fo8poitgfhx4.cloudfront.net/photos/lake-by-the-mountains.jpg?ver=1',
    },
    size: { width: 2000, height: 1333, aspect: Math.floor(2000 / 1333) },
    exif: {
      camera: 'FUJIFILM X-S10',
      lens: 'FUJINON XF 18-55mm F2.8-4',
      aperture: 'f/9',
      exposureTime: '1/140 sec',
      iso: 'ISO-400',
      exposureComp: '+0.7 EV',
      focalLength: '55mm',
    },
    location: 'Ohrid, North Macedonia',
    icons: ['favorite'],
  },
  {
    title: 'Raft on the Mountain Lake',
    slug: 'raft-on-the-mountain-lake',
    uri: 'https://d3fo8poitgfhx4.cloudfront.net/photos/raft-on-the-mountain-lake.jpg?ver=1',
    sizes: {
      xs: 'https://d3fo8poitgfhx4.cloudfront.net/photos/raft-on-the-mountain-lake-w_300.jpg',
      sm: 'https://d3fo8poitgfhx4.cloudfront.net/photos/raft-on-the-mountain-lake-w_450.jpg',
      md: 'https://d3fo8poitgfhx4.cloudfront.net/photos/raft-on-the-mountain-lake-w_600.jpg',
      lg: 'https://d3fo8poitgfhx4.cloudfront.net/photos/raft-on-the-mountain-lake-w_768.jpg',
      xl: 'https://d3fo8poitgfhx4.cloudfront.net/photos/raft-on-the-mountain-lake-w_1000.jpg',
      full: 'https://d3fo8poitgfhx4.cloudfront.net/photos/raft-on-the-mountain-lake.jpg?ver=1',
    },
    size: { width: 2000, height: 3000, aspect: Math.floor(2000 / 3000) },
    exif: {
      camera: 'FUJIFILM X-S10',
      lens: 'FUJINON XF 18-55mm F2.8-4',
      aperture: 'f/9',
      exposureTime: '1/60 sec',
      iso: 'ISO-400',
      exposureComp: '+0.3 EV',
      focalLength: '34mm',
    },
    location: 'Ohrid, North Macedonia',
  },
  {
    title: 'Church by the Mountain Lake',
    slug: 'church-by-the-mountain-lake',
    uri: 'https://d3fo8poitgfhx4.cloudfront.net/photos/church-by-the-mountain-lake.jpg?ver=1',
    sizes: {
      xs: 'https://d3fo8poitgfhx4.cloudfront.net/photos/church-by-the-mountain-lake-w_300.jpg',
      sm: 'https://d3fo8poitgfhx4.cloudfront.net/photos/church-by-the-mountain-lake-w_450.jpg',
      md: 'https://d3fo8poitgfhx4.cloudfront.net/photos/church-by-the-mountain-lake-w_600.jpg',
      lg: 'https://d3fo8poitgfhx4.cloudfront.net/photos/church-by-the-mountain-lake-w_768.jpg',
      xl: 'https://d3fo8poitgfhx4.cloudfront.net/photos/church-by-the-mountain-lake-w_1000.jpg',
      full: 'https://d3fo8poitgfhx4.cloudfront.net/photos/church-by-the-mountain-lake.jpg?ver=1',
    },
    size: { width: 2000, height: 2666, aspect: Math.floor(2000 / 2666) },
    exif: {
      camera: 'FUJIFILM X-S10',
      lens: 'FUJINON XF 18-55mm F2.8-4',
      aperture: 'f/9',
      exposureTime: '1/35 sec',
      iso: 'ISO-400',
      exposureComp: '+0.3 EV',
      focalLength: '32mm',
    },
    location: 'Ohrid, North Macedonia',
  },
  {
    title: 'Boardwalk by the Mountain Lake',
    slug: 'boardwalk-by-the-mountain-lake',
    uri: 'https://d3fo8poitgfhx4.cloudfront.net/photos/boardwalk-by-the-mountain-lake.jpg?ver=1',
    sizes: {
      xs: 'https://d3fo8poitgfhx4.cloudfront.net/photos/boardwalk-by-the-mountain-lake-w_300.jpg',
      sm: 'https://d3fo8poitgfhx4.cloudfront.net/photos/boardwalk-by-the-mountain-lake-w_450.jpg',
      md: 'https://d3fo8poitgfhx4.cloudfront.net/photos/boardwalk-by-the-mountain-lake-w_600.jpg',
      lg: 'https://d3fo8poitgfhx4.cloudfront.net/photos/boardwalk-by-the-mountain-lake-w_768.jpg',
      xl: 'https://d3fo8poitgfhx4.cloudfront.net/photos/boardwalk-by-the-mountain-lake-w_1000.jpg',
      full: 'https://d3fo8poitgfhx4.cloudfront.net/photos/boardwalk-by-the-mountain-lake.jpg?ver=1',
    },
    size: { width: 2000, height: 3000, aspect: Math.floor(2000 / 3000) },
    exif: {
      camera: 'FUJIFILM X-S10',
      lens: 'FUJINON XF 18-55mm F2.8-4',
      aperture: 'f/9',
      exposureTime: '1/105 sec',
      iso: 'ISO-320',
      exposureComp: '-0.7 EV',
      focalLength: '34mm',
    },
    location: 'Ohrid, North Macedonia',
    icons: ['favorite'],
  },
  {
    title: 'Sunlight Through Stained Glass',
    slug: 'sunlight-through-stained-glass',
    uri: 'https://d3fo8poitgfhx4.cloudfront.net/photos/sunlight-through-stained-glass.jpg?ver=1',
    sizes: {
      xs: 'https://d3fo8poitgfhx4.cloudfront.net/photos/sunlight-through-stained-glass-w_300.jpg',
      sm: 'https://d3fo8poitgfhx4.cloudfront.net/photos/sunlight-through-stained-glass-w_450.jpg',
      md: 'https://d3fo8poitgfhx4.cloudfront.net/photos/sunlight-through-stained-glass-w_600.jpg',
      lg: 'https://d3fo8poitgfhx4.cloudfront.net/photos/sunlight-through-stained-glass-w_768.jpg',
      xl: 'https://d3fo8poitgfhx4.cloudfront.net/photos/sunlight-through-stained-glass-w_1000.jpg',
      full: 'https://d3fo8poitgfhx4.cloudfront.net/photos/sunlight-through-stained-glass.jpg?ver=1',
    },
    size: { width: 2000, height: 1333, aspect: Math.floor(2000 / 1333) },
    exif: {
      camera: 'FUJIFILM X-S10',
      lens: 'FUJINON XF 18-55mm F2.8-4',
      aperture: 'f/3.2',
      exposureTime: '1/3200 sec',
      iso: 'ISO-640',
      exposureComp: '-2 EV',
      focalLength: '22mm',
    },
    location: 'Ayvalık, Turkey',
  },
  {
    title: 'Two Ducks Preening',
    slug: 'two-ducks-preening',
    uri: 'https://d3fo8poitgfhx4.cloudfront.net/photos/two-ducks-preening.jpg?ver=1',
    sizes: {
      xs: 'https://d3fo8poitgfhx4.cloudfront.net/photos/two-ducks-preening-w_300.jpg',
      sm: 'https://d3fo8poitgfhx4.cloudfront.net/photos/two-ducks-preening-w_450.jpg',
      md: 'https://d3fo8poitgfhx4.cloudfront.net/photos/two-ducks-preening-w_600.jpg',
      lg: 'https://d3fo8poitgfhx4.cloudfront.net/photos/two-ducks-preening-w_768.jpg',
      xl: 'https://d3fo8poitgfhx4.cloudfront.net/photos/two-ducks-preening-w_1000.jpg',
      full: 'https://d3fo8poitgfhx4.cloudfront.net/photos/two-ducks-preening.jpg?ver=1',
    },
    size: { width: 2000, height: 1600, aspect: Math.floor(2000 / 1600) },
    exif: {
      camera: 'FUJIFILM X-S10',
      lens: 'FUJINON XF 70-300mm F4-5.6',
      aperture: 'f/6.4',
      exposureTime: '1/250 sec',
      iso: 'ISO-400',
      exposureComp: '0 EV',
      focalLength: '300mm',
    },
    location: 'Istanbul, Turkey',
  },
  {
    title: 'Sunset Horizon Over Distance',
    slug: 'sunset-horizon-over-distance',
    uri: 'https://d3fo8poitgfhx4.cloudfront.net/photos/sunset-horizon-over-distance.jpg?ver=1',
    sizes: {
      xs: 'https://d3fo8poitgfhx4.cloudfront.net/photos/sunset-horizon-over-distance-w_300.jpg',
      sm: 'https://d3fo8poitgfhx4.cloudfront.net/photos/sunset-horizon-over-distance-w_450.jpg',
      md: 'https://d3fo8poitgfhx4.cloudfront.net/photos/sunset-horizon-over-distance-w_600.jpg',
      lg: 'https://d3fo8poitgfhx4.cloudfront.net/photos/sunset-horizon-over-distance-w_768.jpg',
      xl: 'https://d3fo8poitgfhx4.cloudfront.net/photos/sunset-horizon-over-distance-w_1000.jpg',
      full: 'https://d3fo8poitgfhx4.cloudfront.net/photos/sunset-horizon-over-distance.jpg?ver=1',
    },
    size: { width: 2000, height: 1333, aspect: Math.floor(2000 / 1333) },
    exif: {
      camera: 'FUJIFILM X-S10',
      lens: 'FUJINON XF 18-55mm F2.8-4',
      aperture: 'f/7.1',
      exposureTime: '1/210 sec',
      iso: 'ISO-400',
      exposureComp: '0 EV',
      focalLength: '70mm',
    },
    location: 'Bodrum, Turkey',
  },
  {
    title: 'Train Rails Split Four',
    slug: 'train-rails-split-four',
    uri: 'https://d3fo8poitgfhx4.cloudfront.net/photos/train-rails-split-four.jpg?ver=1',
    sizes: {
      xs: 'https://d3fo8poitgfhx4.cloudfront.net/photos/train-rails-split-four-w_300.jpg',
      sm: 'https://d3fo8poitgfhx4.cloudfront.net/photos/train-rails-split-four-w_450.jpg',
      md: 'https://d3fo8poitgfhx4.cloudfront.net/photos/train-rails-split-four-w_600.jpg',
      lg: 'https://d3fo8poitgfhx4.cloudfront.net/photos/train-rails-split-four-w_768.jpg',
      xl: 'https://d3fo8poitgfhx4.cloudfront.net/photos/train-rails-split-four-w_1000.jpg',
      full: 'https://d3fo8poitgfhx4.cloudfront.net/photos/train-rails-split-four.jpg?ver=1',
    },
    size: { width: 2000, height: 3000, aspect: Math.floor(2000 / 3000) },
    exif: {
      camera: 'FUJIFILM X-S10',
      lens: 'FUJINON XF 18-55mm F2.8-4',
      aperture: 'f/22',
      exposureTime: '1/80 sec',
      iso: 'ISO-400',
      exposureComp: '-0.7 EV',
      focalLength: '26mm',
    },
    location: 'Istanbul, Turkey',
  },
  {
    title: 'Train Clock in Station',
    slug: 'train-clock-in-station',
    uri: 'https://d3fo8poitgfhx4.cloudfront.net/photos/train-clock-in-station.jpg?ver=1',
    sizes: {
      xs: 'https://d3fo8poitgfhx4.cloudfront.net/photos/train-clock-in-station-w_300.jpg',
      sm: 'https://d3fo8poitgfhx4.cloudfront.net/photos/train-clock-in-station-w_450.jpg',
      md: 'https://d3fo8poitgfhx4.cloudfront.net/photos/train-clock-in-station-w_600.jpg',
      lg: 'https://d3fo8poitgfhx4.cloudfront.net/photos/train-clock-in-station-w_768.jpg',
      xl: 'https://d3fo8poitgfhx4.cloudfront.net/photos/train-clock-in-station-w_1000.jpg',
      full: 'https://d3fo8poitgfhx4.cloudfront.net/photos/train-clock-in-station.jpg?ver=1',
    },
    size: { width: 2000, height: 3000, aspect: Math.floor(2000 / 3000) },
    exif: {
      camera: 'FUJIFILM X-S10',
      lens: 'FUJINON XF 18-55mm F2.8-4',
      aperture: 'f/22',
      exposureTime: '1/10 sec',
      iso: 'ISO-400',
      exposureComp: '-0.3 EV',
      focalLength: '18mm',
    },
    location: 'Istanbul, Turkey',
  },
  {
    title: 'Old Town Colors',
    slug: 'old-town-colors',
    uri: 'https://d3fo8poitgfhx4.cloudfront.net/photos/old-town-colors.jpg?ver=1',
    sizes: {
      xs: 'https://d3fo8poitgfhx4.cloudfront.net/photos/old-town-colors-w_300.jpg',
      sm: 'https://d3fo8poitgfhx4.cloudfront.net/photos/old-town-colors-w_450.jpg',
      md: 'https://d3fo8poitgfhx4.cloudfront.net/photos/old-town-colors-w_600.jpg',
      lg: 'https://d3fo8poitgfhx4.cloudfront.net/photos/old-town-colors-w_768.jpg',
      xl: 'https://d3fo8poitgfhx4.cloudfront.net/photos/old-town-colors-w_1000.jpg',
      full: 'https://d3fo8poitgfhx4.cloudfront.net/photos/old-town-colors.jpg?ver=1',
    },
    size: { width: 2000, height: 2667, aspect: Math.floor(2000 / 2667) },
    exif: {
      camera: 'FUJIFILM X-S10',
      lens: 'FUJINON XF 18-55mm F2.8-4',
      aperture: 'f/9',
      exposureTime: '1/105 sec',
      iso: 'ISO-400',
      exposureComp: '0 EV',
      focalLength: '44mm',
    },
    location: 'Istanbul, Turkey',
  },
  {
    title: 'Church Between Old Houses',
    slug: 'church-between-old-houses',
    uri: 'https://d3fo8poitgfhx4.cloudfront.net/photos/church-between-old-houses.jpg?ver=1',
    sizes: {
      xs: 'https://d3fo8poitgfhx4.cloudfront.net/photos/church-between-old-houses-w_300.jpg',
      sm: 'https://d3fo8poitgfhx4.cloudfront.net/photos/church-between-old-houses-w_450.jpg',
      md: 'https://d3fo8poitgfhx4.cloudfront.net/photos/church-between-old-houses-w_600.jpg',
      lg: 'https://d3fo8poitgfhx4.cloudfront.net/photos/church-between-old-houses-w_768.jpg',
      xl: 'https://d3fo8poitgfhx4.cloudfront.net/photos/church-between-old-houses-w_1000.jpg',
      full: 'https://d3fo8poitgfhx4.cloudfront.net/photos/church-between-old-houses.jpg?ver=1',
    },
    size: { width: 2000, height: 3000, aspect: Math.floor(2000 / 3000) },
    exif: {
      camera: 'FUJIFILM X-S10',
      lens: 'FUJINON XF 18-55mm F2.8-4',
      aperture: 'f/9',
      exposureTime: '1/110 sec',
      iso: 'ISO-400',
      exposureComp: '0 EV',
      focalLength: '39mm',
    },
    location: 'Istanbul, Turkey',
  },
  {
    title: 'Red Ferrari New Year’s',
    slug: 'red-ferrari-new-years',
    uri: 'https://d3fo8poitgfhx4.cloudfront.net/photos/red-ferrari-new-years.jpg?ver=1',
    sizes: {
      xs: 'https://d3fo8poitgfhx4.cloudfront.net/photos/red-ferrari-new-years-w_300.jpg',
      sm: 'https://d3fo8poitgfhx4.cloudfront.net/photos/red-ferrari-new-years-w_450.jpg',
      md: 'https://d3fo8poitgfhx4.cloudfront.net/photos/red-ferrari-new-years-w_600.jpg',
      lg: 'https://d3fo8poitgfhx4.cloudfront.net/photos/red-ferrari-new-years-w_768.jpg',
      xl: 'https://d3fo8poitgfhx4.cloudfront.net/photos/red-ferrari-new-years-w_1000.jpg',
      full: 'https://d3fo8poitgfhx4.cloudfront.net/photos/red-ferrari-new-years.jpg?ver=1',
    },
    size: { width: 2000, height: 2666, aspect: Math.floor(2000 / 2666) },
    exif: {
      camera: 'FUJIFILM X-S10',
      lens: 'FUJINON XF 18-55mm F2.8-4',
      aperture: 'f/4',
      exposureTime: '1/160 sec',
      iso: 'ISO-3200',
      exposureComp: '-1.3 EV',
      focalLength: '55mm',
    },
    location: 'Istanbul, Turkey',
  },
  {
    title: 'New Year’s Tree at Night',
    slug: 'new-years-tree-at-night',
    uri: 'https://d3fo8poitgfhx4.cloudfront.net/photos/new-years-tree-at-night.jpg?ver=1',
    sizes: {
      xs: 'https://d3fo8poitgfhx4.cloudfront.net/photos/new-years-tree-at-night-w_300.jpg',
      sm: 'https://d3fo8poitgfhx4.cloudfront.net/photos/new-years-tree-at-night-w_450.jpg',
      md: 'https://d3fo8poitgfhx4.cloudfront.net/photos/new-years-tree-at-night-w_600.jpg',
      lg: 'https://d3fo8poitgfhx4.cloudfront.net/photos/new-years-tree-at-night-w_768.jpg',
      xl: 'https://d3fo8poitgfhx4.cloudfront.net/photos/new-years-tree-at-night-w_1000.jpg',
      full: 'https://d3fo8poitgfhx4.cloudfront.net/photos/new-years-tree-at-night.jpg?ver=1',
    },
    size: { width: 2000, height: 2667, aspect: Math.floor(2000 / 2667) },
    exif: {
      camera: 'FUJIFILM X-S10',
      lens: 'FUJINON XF 18-55mm F2.8-4',
      aperture: 'f/4',
      exposureTime: '1/60 sec',
      iso: 'ISO-3200',
      exposureComp: '-1.3 EV',
      focalLength: '34mm',
    },
    location: 'Istanbul, Turkey',
  },
  {
    slug: 'tour-of-turkey-2023',
    title: 'Tour of Turkey 2023',
    uri: 'https://d3fo8poitgfhx4.cloudfront.net/photos/tour-of-turkey-2023.jpg?ver=1',
    sizes: {
      xs: 'https://d3fo8poitgfhx4.cloudfront.net/photos/tour-of-turkey-2023-w_300.jpg',
      sm: 'https://d3fo8poitgfhx4.cloudfront.net/photos/tour-of-turkey-2023-w_450.jpg',
      md: 'https://d3fo8poitgfhx4.cloudfront.net/photos/tour-of-turkey-2023-w_600.jpg',
      lg: 'https://d3fo8poitgfhx4.cloudfront.net/photos/tour-of-turkey-2023-w_768.jpg',
      xl: 'https://d3fo8poitgfhx4.cloudfront.net/photos/tour-of-turkey-2023-w_1000.jpg',
      full: 'https://d3fo8poitgfhx4.cloudfront.net/photos/tour-of-turkey-2023.jpg?ver=1',
    },
    size: { width: 2000, height: 2667, aspect: Math.floor(2000 / 2667) },
    exif: {
      camera: 'FUJIFILM X-S10',
      lens: 'FUJINON XF 18-55mm F2.8-4',
      aperture: 'f/4',
      exposureTime: '1/4000 sec',
      iso: 'ISO-320',
      exposureComp: '0 EV',
      focalLength: '18mm',
    },
    location: 'Istanbul, Turkey',
  },
  {
    title: 'Colorful Dove by the Window',
    slug: 'colorful-dove-by-the-window',
    uri: 'https://d3fo8poitgfhx4.cloudfront.net/photos/colorful-dove-by-the-window.jpg?ver=1',
    sizes: {
      xs: 'https://d3fo8poitgfhx4.cloudfront.net/photos/colorful-dove-by-the-window-w_300.jpg',
      sm: 'https://d3fo8poitgfhx4.cloudfront.net/photos/colorful-dove-by-the-window-w_450.jpg',
      md: 'https://d3fo8poitgfhx4.cloudfront.net/photos/colorful-dove-by-the-window-w_600.jpg',
      lg: 'https://d3fo8poitgfhx4.cloudfront.net/photos/colorful-dove-by-the-window-w_768.jpg',
      xl: 'https://d3fo8poitgfhx4.cloudfront.net/photos/colorful-dove-by-the-window-w_1000.jpg',
      full: 'https://d3fo8poitgfhx4.cloudfront.net/photos/colorful-dove-by-the-window.jpg?ver=1',
    },
    size: { width: 2000, height: 3000, aspect: Math.floor(2000 / 3000) },
    exif: {
      camera: 'FUJIFILM X-S10',
      lens: 'FUJINON XF 18-55mm F2.8-4',
      aperture: 'f/4',
      exposureTime: '1/30 sec',
      iso: 'ISO-400',
      exposureComp: '0 EV',
      focalLength: '55mm',
    },
    location: 'Istanbul, Turkey',
  },
  {
    title: 'Sunlit Cat Through Grass',
    slug: 'sunlit-cat-through-grass',
    uri: 'https://d3fo8poitgfhx4.cloudfront.net/photos/sunlit-cat-through-grass.jpg?ver=1',
    sizes: {
      xs: 'https://d3fo8poitgfhx4.cloudfront.net/photos/sunlit-cat-through-grass-w_300.jpg',
      sm: 'https://d3fo8poitgfhx4.cloudfront.net/photos/sunlit-cat-through-grass-w_450.jpg',
      md: 'https://d3fo8poitgfhx4.cloudfront.net/photos/sunlit-cat-through-grass-w_600.jpg',
      lg: 'https://d3fo8poitgfhx4.cloudfront.net/photos/sunlit-cat-through-grass-w_768.jpg',
      xl: 'https://d3fo8poitgfhx4.cloudfront.net/photos/sunlit-cat-through-grass-w_1000.jpg',
      full: 'https://d3fo8poitgfhx4.cloudfront.net/photos/sunlit-cat-through-grass.jpg?ver=1',
    },
    size: { width: 2000, height: 3000, aspect: Math.floor(2000 / 3000) },
    exif: {
      camera: 'FUJIFILM X-S10',
      lens: 'FUJINON XF 18-55mm F2.8-4',
      aperture: 'f/4',
      exposureTime: '1/1000 sec',
      iso: 'ISO-400',
      exposureComp: '0 EV',
      focalLength: '48mm',
    },
    location: 'Istanbul, Turkey',
  },
  {
    title: 'Galata Vibes From Tower',
    slug: 'galata-vibes-from-tower',
    uri: 'https://d3fo8poitgfhx4.cloudfront.net/photos/galata-vibes-from-tower.jpg?ver=1',
    sizes: {
      xs: 'https://d3fo8poitgfhx4.cloudfront.net/photos/galata-vibes-from-tower-w_300.jpg',
      sm: 'https://d3fo8poitgfhx4.cloudfront.net/photos/galata-vibes-from-tower-w_450.jpg',
      md: 'https://d3fo8poitgfhx4.cloudfront.net/photos/galata-vibes-from-tower-w_600.jpg',
      lg: 'https://d3fo8poitgfhx4.cloudfront.net/photos/galata-vibes-from-tower-w_768.jpg',
      xl: 'https://d3fo8poitgfhx4.cloudfront.net/photos/galata-vibes-from-tower-w_1000.jpg',
      full: 'https://d3fo8poitgfhx4.cloudfront.net/photos/galata-vibes-from-tower.jpg?ver=1',
    },
    size: { width: 2000, height: 2667, aspect: Math.floor(2000 / 2667) },
    exif: {
      camera: 'FUJIFILM X-S10',
      lens: 'FUJINON XF 18-55mm F2.8-4',
      aperture: 'f/4',
      exposureTime: '1/800 sec',
      iso: 'ISO-800',
      exposureComp: '0 EV',
      focalLength: '41mm',
    },
    location: 'Istanbul, Turkey',
  },
  {
    title: 'Drip Coffee by the Plant',
    slug: 'drip-coffee-by-the-plant',
    uri: 'https://d3fo8poitgfhx4.cloudfront.net/photos/drip-coffee-by-the-plant.jpg?ver=1',
    sizes: {
      xs: 'https://d3fo8poitgfhx4.cloudfront.net/photos/drip-coffee-by-the-plant-w_300.jpg',
      sm: 'https://d3fo8poitgfhx4.cloudfront.net/photos/drip-coffee-by-the-plant-w_450.jpg',
      md: 'https://d3fo8poitgfhx4.cloudfront.net/photos/drip-coffee-by-the-plant-w_600.jpg',
      lg: 'https://d3fo8poitgfhx4.cloudfront.net/photos/drip-coffee-by-the-plant-w_768.jpg',
      xl: 'https://d3fo8poitgfhx4.cloudfront.net/photos/drip-coffee-by-the-plant-w_1000.jpg',
      full: 'https://d3fo8poitgfhx4.cloudfront.net/photos/drip-coffee-by-the-plant.jpg?ver=1',
    },
    size: { width: 2000, height: 3000, aspect: Math.floor(2000 / 3000) },
    exif: {
      camera: 'FUJIFILM X-S10',
      lens: 'FUJINON XF 18-55mm F2.8-4',
      aperture: 'f/4',
      exposureTime: '1/25 sec',
      iso: 'ISO-800',
      exposureComp: '0 EV',
      focalLength: '55mm',
    },
    location: 'Istanbul, Turkey',
  },
];

const slugToImageData: GalleryItemsMap = new Map<string, ImageItem>();
imgGroup1.forEach((item) => {
  slugToImageData.set(item.slug, {
    ...item,
    blurDataURL: blurDataUrls[item.slug],
  });
});
imgGroup2.forEach((item) => {
  slugToImageData.set(item.slug, {
    ...item,
    blurDataURL: blurDataUrls[item.slug],
  });
});

export { slugToImageData };

export const playlist: PlaylistItems = [
  {
    title: 'Toz',
    artist: 'Jakuzi',
    image:
      'https://d3fo8poitgfhx4.cloudfront.net/playlist/toz-jakuzi-cover.jpg',
  },
  {
    title: 'Koca Bir Saçmalık',
    artist: 'Jakuzi',
    image:
      'https://d3fo8poitgfhx4.cloudfront.net/playlist/koca-bir-sacmalik-jakuzi-cover.jpg',
  },
  {
    title: "Don't You Remember",
    artist: 'Adele',
    image:
      'https://d3fo8poitgfhx4.cloudfront.net/playlist/dont-you-remember-adele-cover.jpg',
  },
  {
    title: 'I Belong to You',
    artist: 'Brandi Carlile',
    image:
      'https://d3fo8poitgfhx4.cloudfront.net/playlist/i-belong-to-you-brandi-carlile-cover.jpg',
  },
  {
    title: 'Melt My Heart to Stone',
    artist: 'Adele',
    image:
      'https://d3fo8poitgfhx4.cloudfront.net/playlist/melt-my-heart-to-stone-adele-cover.jpg',
  },
];
